/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthAnalysisSymbolRouteImport } from './routes/_auth/analysis/$symbol'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthProfileIndexRouteImport } from './routes/_auth/profile/index'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AuthSessionIndexRouteImport } from './routes/_auth/session/index'
import { Route as AuthSettingsCredentialsRouteImport } from './routes/_auth/settings/credentials'
import { Route as AuthSettingsTokensRouteImport } from './routes/_auth/settings/tokens'
import { Route as AuthSettingsTradingRouteImport } from './routes/_auth/settings/trading'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as FaqCategoryIdRouteImport } from './routes/faq/$categoryId'
import { Route as IndexRouteImport } from './routes/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqCategoryIdRoute = FaqCategoryIdRouteImport.update({
  id: '/faq/$categoryId',
  path: '/faq/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSessionIndexRoute = AuthSessionIndexRouteImport.update({
  id: '/session/',
  path: '/session/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProfileIndexRoute = AuthProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSettingsTradingRoute = AuthSettingsTradingRouteImport.update({
  id: '/settings/trading',
  path: '/settings/trading',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsTokensRoute = AuthSettingsTokensRouteImport.update({
  id: '/settings/tokens',
  path: '/settings/tokens',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsCredentialsRoute = AuthSettingsCredentialsRouteImport.update({
  id: '/settings/credentials',
  path: '/settings/credentials',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAnalysisSymbolRoute = AuthAnalysisSymbolRouteImport.update({
  id: '/analysis/$symbol',
  path: '/analysis/$symbol',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/faq/$categoryId': typeof FaqCategoryIdRoute
  '/analysis/$symbol': typeof AuthAnalysisSymbolRoute
  '/settings/credentials': typeof AuthSettingsCredentialsRoute
  '/settings/tokens': typeof AuthSettingsTokensRoute
  '/settings/trading': typeof AuthSettingsTradingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/profile/': typeof AuthProfileIndexRoute
  '/session/': typeof AuthSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/faq/$categoryId': typeof FaqCategoryIdRoute
  '/analysis/$symbol': typeof AuthAnalysisSymbolRoute
  '/settings/credentials': typeof AuthSettingsCredentialsRoute
  '/settings/tokens': typeof AuthSettingsTokensRoute
  '/settings/trading': typeof AuthSettingsTradingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/profile': typeof AuthProfileIndexRoute
  '/session': typeof AuthSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteRouteWithChildren
  '/api/health': typeof ApiHealthRoute
  '/faq/$categoryId': typeof FaqCategoryIdRoute
  '/_auth/analysis/$symbol': typeof AuthAnalysisSymbolRoute
  '/_auth/settings/credentials': typeof AuthSettingsCredentialsRoute
  '/_auth/settings/tokens': typeof AuthSettingsTokensRoute
  '/_auth/settings/trading': typeof AuthSettingsTradingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/profile/': typeof AuthProfileIndexRoute
  '/_auth/session/': typeof AuthSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/health'
    | '/faq/$categoryId'
    | '/analysis/$symbol'
    | '/settings/credentials'
    | '/settings/tokens'
    | '/settings/trading'
    | '/api/auth/$'
    | '/dashboard/'
    | '/profile/'
    | '/session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/health'
    | '/faq/$categoryId'
    | '/analysis/$symbol'
    | '/settings/credentials'
    | '/settings/tokens'
    | '/settings/trading'
    | '/api/auth/$'
    | '/dashboard'
    | '/profile'
    | '/session'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/api/health'
    | '/faq/$categoryId'
    | '/_auth/analysis/$symbol'
    | '/_auth/settings/credentials'
    | '/_auth/settings/tokens'
    | '/_auth/settings/trading'
    | '/api/auth/$'
    | '/_auth/dashboard/'
    | '/_auth/profile/'
    | '/_auth/session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  ApiHealthRoute: typeof ApiHealthRoute
  FaqCategoryIdRoute: typeof FaqCategoryIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq/$categoryId': {
      id: '/faq/$categoryId'
      path: '/faq/$categoryId'
      fullPath: '/faq/$categoryId'
      preLoaderRoute: typeof FaqCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/session/': {
      id: '/_auth/session/'
      path: '/session'
      fullPath: '/session/'
      preLoaderRoute: typeof AuthSessionIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/profile/': {
      id: '/_auth/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthProfileIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/settings/trading': {
      id: '/_auth/settings/trading'
      path: '/settings/trading'
      fullPath: '/settings/trading'
      preLoaderRoute: typeof AuthSettingsTradingRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/tokens': {
      id: '/_auth/settings/tokens'
      path: '/settings/tokens'
      fullPath: '/settings/tokens'
      preLoaderRoute: typeof AuthSettingsTokensRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/credentials': {
      id: '/_auth/settings/credentials'
      path: '/settings/credentials'
      fullPath: '/settings/credentials'
      preLoaderRoute: typeof AuthSettingsCredentialsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/analysis/$symbol': {
      id: '/_auth/analysis/$symbol'
      path: '/analysis/$symbol'
      fullPath: '/analysis/$symbol'
      preLoaderRoute: typeof AuthAnalysisSymbolRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAnalysisSymbolRoute: typeof AuthAnalysisSymbolRoute
  AuthSettingsCredentialsRoute: typeof AuthSettingsCredentialsRoute
  AuthSettingsTokensRoute: typeof AuthSettingsTokensRoute
  AuthSettingsTradingRoute: typeof AuthSettingsTradingRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthProfileIndexRoute: typeof AuthProfileIndexRoute
  AuthSessionIndexRoute: typeof AuthSessionIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAnalysisSymbolRoute: AuthAnalysisSymbolRoute,
  AuthSettingsCredentialsRoute: AuthSettingsCredentialsRoute,
  AuthSettingsTokensRoute: AuthSettingsTokensRoute,
  AuthSettingsTradingRoute: AuthSettingsTradingRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthProfileIndexRoute: AuthProfileIndexRoute,
  AuthSessionIndexRoute: AuthSessionIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  ApiHealthRoute: ApiHealthRoute,
  FaqCategoryIdRoute: FaqCategoryIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
